// models/PlatformModel/Enums/ActivityLogEnum.js

export const LogActionType = Object.freeze({
  // --- TICKET MANAGEMENT ---
  TICKET_CREATE: 'TICKET_CREATE',
  TICKET_UPDATE: 'TICKET_UPDATE',
  TICKET_DELETE: 'TICKET_DELETE',
  TICKET_ASSIGN: 'TICKET_ASSIGN',
  TICKET_COMMENT: 'TICKET_COMMENT',
  TICKET_ATTACHMENT_UPLOAD: 'TICKET_ATTACHMENT_UPLOAD',
  TICKET_MOVE: 'TICKET_MOVE',
  TICKET_TRANSITION: 'TICKET_TRANSITION',

  // --- SPRINT MANAGEMENT ---
  SPRINT_CREATE: 'SPRINT_CREATE',
  SPRINT_START: 'SPRINT_START',
  SPRINT_COMPLETE: 'SPRINT_COMPLETE',
  SPRINT_UPDATE: 'SPRINT_UPDATE',

  // --- TIME TRACKING / WORKLOG ---
  WORKLOG_ADD: 'WORKLOG_ADD',
  WORKLOG_UPDATE: 'WORKLOG_UPDATE',
  WORKLOG_DELETE: 'WORKLOG_DELETE',
  ADD_TIME_LOG:'ADD_TIME_LOG',

  // --- USER & PROJECT ---
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  PROJECT_CREATE: 'PROJECT_CREATE',
  PROJECT_ARCHIVE: 'PROJECT_ARCHIVE',

  // --- VIEW / AUDIT ---
  VIEW_DETAILS: 'VIEW_DETAILS',
});

export const LogEntityType = Object.freeze({
  PROJECT: 'PROJECT',
  BOARD: 'BOARD',
  SPRINT: 'SPRINT',
  ISSUE: 'ISSUE',
  WORKFLOW: 'WORKFLOW',
  COMMENT: 'COMMENT',
  ATTACHMENT: 'ATTACHMENT',
  WORKLOG: 'WORKLOG',
  USER: 'USER',
  OTHER: 'OTHER',
  TASK:'TASK'
});
